
services:
  rundeck:
    container_name: rundeck
    build:
      context: rundeck
      args:
        RUNDECK_IMAGE: ${RUNDECK_IMAGE}
    links:
      - mysql
    environment:
      RUNDECK_GRAILS_URL: http://192.168.1.16:4440
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      RUNDECK_SERVER_ADDRESS: 0.0.0.0
      RUNDECK_TOKENS_FILE: /home/rundeck/etc/tokens.properties
      RUNDECK_METRICS_ENABLED: true
    ports:
      - 4440:4440
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f http://192.168.1.16:4440"
      interval: 1s
      retries: 120
    volumes:
      - ./scripts:/var/lib/rundeck/scripts
      - ./config:/var/lib/rundeck/config
      - ./jobs:/var/lib/rundeck/jobs
      - ./data/rundeck:/home/rundeck/server/data # Verifique se o diretório existe e possui permissões corretas no host Windows

  mysql:
    container_name: mysql
    image: mysql:8.4.2
    expose:
      - 3306
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck

  rundeck_exporter:
    container_name: rundeck_exporter
    build:
      context: rundeck_exporter
    depends_on:
      rundeck:
        condition: service_healthy
    environment:
      RUNDECK_EXPORTER_HOST: 0.0.0.0
      RUNDECK_EXPORTER_DEBUG: "true"
      RUNDECK_URL: http://192.168.1.16:4440
      RUNDECK_TOKEN: rundecktoken
      RUNDECK_PROJECTS_EXECUTIONS: "true"
      RUNDECK_CPU_STATS: "true"
      RUNDECK_MEMORY_STATS: "true"
    ports:
      - 9620:9620
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"

